---
- name: Download Openshift Operators
  hosts: localhost
  tasks:
    - name: Setting up workload for user
      debug:
        msg: "Building Catalog Source"

    - name: Get the manifests
      command: "oc adm catalog build --appregistry-endpoint {{ appregistry_endpoint }} --appregistry-org {{ appregistry_org }} --manifest-dir={{ appregistry_org }} manifests"
      vars:
        appregistry_endpoint: "https://quay.io/cnr"
        appregistry_org: "redhat-operators"

    # Leave this as the last task in the playbook.
    - name: tasks complete
      debug:
        msg: "Build Catalog Source Tasks completed successfully."
      when: not silent|bool