---
- name: Download Openshift Operators
  hosts: localhost
  vars_files:
    vars/main.yml
  tasks:
    - name: Setting up workload for user
      debug:
        msg: "Building Catalog Source"

    - name: Cleaning up manifest dir
      file:
        path: "{{ item }}" 
        state: absent
      with_items:
        - "{{ inventory_dir }}/{{ appregistry_org }}"
        - "{{ inventory_dir }}/filtered-manifests"

    - name: Get all manifests
      command: >-
        oc adm catalog build 
          --appregistry-endpoint {{ appregistry_endpoint }} 
          --appregistry-org {{ appregistry_org }} 
          --manifest-dir="{{ inventory_dir }}/{{ appregistry_org }}"

    - name: Find Operators to deploy
      find:
        paths: "{{ inventory_dir }}/{{ appregistry_org }}"
        recurse: yes
        file_type: directory
        patterns: ["3scale-operator","datagrid"]
      register: operators_to_deploy

    - name: Create the manifest dir
      file:
        path: "{{ inventory_dir }}/filtered-manifests"
        state: directory

    - name: Copy Operators to deploy 
      copy:
        src: "{{ item.path }}"
        dest: "{{ inventory_dir }}/filtered-manifests"
      with_items: 
        - "{{ operators_to_deploy.files }}"

    - name: Build the Catalog Registry Image
      podman_image:
        name: "{{ mirror_endpoint }}/{{ registry_operator_org }}/{{ registry_operator_repo }}:{{ registry_operator_tag }}"
        path: "{{ inventory_dir }}"
        auth_file: "{{ inventory_dir }}/{{ local_secret_json }}"
        build:
          cache: no
          force_rm: yes
          rm: yes
        push: yes
      register: result
      until: result.image is defined 
      retries: 2

    # Leave this as the last task in the playbook.
    - name: tasks complete
      debug:
        msg: "Build Catalog Source Tasks completed successfully."
