---
- name: Download Openshift Operators
  hosts: localhost
  vars_files:
    vars/main.yml
  tasks:
    - name: Setting up workload for user
      debug:
        msg: "Building Catalog Source"

#    - name: Cleaning up manifest dir
#      file:
#        path: "{{ inventory_dir }}/{{ appregistry_org }}" 
#        state: absent

#    - name: Get all manifests
#      command: >-
#        oc adm catalog build 
#          --appregistry-endpoint {{ appregistry_endpoint }} 
#          --appregistry-org {{ appregistry_org }} 
#          --manifest-dir="{{ inventory_dir }}/{{ appregistry_org }}"

    - name: Cleaning up manifest dir
      file:
        path: "{{ inventory_dir }}/{{ appregistry_org }}/manifests"
        state: directory 

    - name: Move manifests to common folder
      command: >-
        mv {{ item }}/* {{ inventory_dir }}/{{ appregistry_org }}/manifests
      with_fileglob:
        - "{{ inventory_dir }}/{{ appregistry_org }}/manifests-*"

    - name: Find all Catalog sources to delete
      find:
        paths: "{{ inventory_dir }}/filtered-manifests"
        recurse: no
        file_type: directory
        excludes: "3scale-operator,datagrid"
      register: operators_to_delete

    - name: Delete Catalog sources not needed
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: 
        - "{{ operators_to_delete.files }}"

    - name: Build the Catalog Registry Image
      podman_image:
        name: "{{ mirror_endpoint }}/{{ registry_operator_org }}/{{ registry_operator_repo }}:{{ registry_operator_tag }}"
        path: "{{ inventory_dir }}"
        auth_file: "{{ inventory_dir }}/{{ local_secret_json }}"
        build:
          cache: no
          force_rm: yes
          rm: yes
        push: yes
      register: result
      until: result.image is defined 
      retries: 2

    # Leave this as the last task in the playbook.
    - name: tasks complete
      debug:
        msg: "Build Catalog Source Tasks completed successfully."
