---
- name: Download Openshift Operators
  hosts: localhost
  vars_files:
    vars/main.yml
  tasks:
    - name: Setting up workload for user
      debug:
        msg: "Building Catalog Source"

    - name: Get all manifests
      command: >-
        oc adm catalog build 
          --appregistry-endpoint {{ appregistry_endpoint }} 
          --appregistry-org {{ appregistry_org }} 
          --manifest-dir="{{ inventory_dir }}/{{ appregistry_org }}-manifests"

    - name: Find all Catalog sources to delete
      find:
        paths: "{{ inventory_dir }}/{{ appregistry_org }}-manifests"
        recurse: no
        file_type: directory
        excludes: '3scale-operator,datagrid'
      register: operators_to_delete

    - name: tasks complete
      debug:
        msg: "LOG >> {{ operators_to_delete }}"

    # Leave this as the last task in the playbook.
    - name: tasks complete
      debug:
        msg: "Build Catalog Source Tasks completed successfully."