---
- name: Configure OperatorHub
  hosts: localhost
  vars_files:
    vars/main.yml
  tasks:
    - name: Setting up workload for user
      debug:
        msg: "Configuring OperatorHub"

    - name: Defines the ImageContentSourcePolicy object that can configure nodes to translate between the image references stored in Operator manifests and the mirrored registry
      command: >-
        oc apply -f "{{ inventory_dir }}/copied-manifests"

    - name: Fill the CatalogSource template
      template:
        src: "{{ inventory_dir }}/templates/catalogsource.yml.j2"
        dest: "{{ inventory_dir }}/catalogsource.yml"

    - name: Create a CatalogSource object that references our catalog image
      command: >-
        oc apply -f {{ inventory_dir }}/catalogsource.yml 

    # Leave this as the last task in the playbook.
    - name: tasks complete
      debug:
        msg: "Configuring OperatorHub Tasks completed successfully."
