- name: Create '{{ organization_name }}' Organization into Quay
  uri:
    url: https://{{ mirror_endpoint }}/api/v1/organization/
    method: POST
    body:
      name: "{{ organization_name }}"
      email: ""
    body_format: json
    headers:
      Authorization: "Bearer {{ token }}"
    status_code: [201, 400]

