---
- name: Setting up workload for user
  debug:
    msg: "Building Catalog Source"

- name: Get all manifests
  command: >-
    oc adm catalog build 
      --appregistry-endpoint {{ appregistry_endpoint }} 
      --appregistry-org {{ appregistry_org }} 
      --manifest-dir="{{ inventory_dir }}/{{ appregistry_org }}"

- name: Find Operators to deploy
  find:
    paths: "{{ inventory_dir }}/{{ appregistry_org }}"
    recurse: yes
    file_type: directory
    patterns: "{{ operator_whitelists }}"
  register: operators_to_deploy

- name: Create the manifest dir
  file:
    path: "{{ inventory_dir }}/filtered-manifests"
    state: directory

- name: Copy Operators to deploy 
  copy:
    src: "{{ item.path }}"
    dest: "{{ inventory_dir }}/filtered-manifests"
  with_items: 
    - "{{ operators_to_deploy.files }}"

- include_role:
    name: create-organization-in-quay
  vars:
    organization_name: "{{ registry_operator_org }}"
    token: "{{ quay.application_token }}"
  when: quay.as_a_mirror_registry

- name: Build the Catalog Registry Image with 'oci' format
  podman_image:
    name: "{{ mirror_endpoint }}/{{ registry_operator_org }}/{{ registry_operator_repo }}:{{ registry_operator_tag }}"
    path: "{{ inventory_dir }}"
    auth_file: "{{ inventory_dir }}/{{ local_secret_json }}"
    build:
      cache: no
      force_rm: yes
      rm: yes
      format: oci
    push: yes
  register: result
  until: result.image is defined 
  retries: 2
  when: quay.as_a_mirror_registry

- name: Build the Catalog Registry Image with 'docker' format
  podman_image:
    name: "{{ mirror_endpoint }}/{{ registry_operator_org }}/{{ registry_operator_repo }}:{{ registry_operator_tag }}"
    path: "{{ inventory_dir }}"
    auth_file: "{{ inventory_dir }}/{{ local_secret_json }}"
    build:
      cache: no
      force_rm: yes
      rm: yes
      format: docker
    push: yes
  register: result
  until: result.image is defined
  retries: 2
  when: not quay.as_a_mirror_registry


# Leave this as the last task in the playbook.
- name: tasks complete
  debug:
    msg: "Build Catalog Source Tasks completed successfully."
